
/* Copyright (c) 2011, Meng Lin, Hua Huang and Robert D. Cameron.
   Licensed under the Academic Free License 3.0.
   This file is generated by the IDISA+ generator;
   modifications should be made only by changing the
   generator configuration and data files. */

#ifndef IDISA128_C_H
#define IDISA128_C_H

#if defined USE_SSE3
#include "idisa_c/idisa_sse3_c.h"
#elif defined USE_SSSE3
#include "idisa_c/idisa_ssse3_c.h"
#elif defined USE_SSE4_1
#include "idisa_c/idisa_sse4_1_c.h"
#elif defined USE_SSE4_2
#include "idisa_c/idisa_sse4_2_c.h"
#else
#include "idisa_c/idisa_sse2_c.h"
#endif 
   
typedef bitblock128_t BitBlock;
#endif
